[package]
name = 'cord-primitives'
version = '0.2.0'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']

[dependencies]
serde = { version = "1.0.118", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[dev-dependencies]
frame-support = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"sp-core/std",
	"sp-std/std",
]