[package]
name = 'cord-primitives'
version = '0.5.3'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']

[dependencies]
serde = { version = "1.0.23", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["bit-vec", "derive"] }
sp-core = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9"}
frame-system = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9"}
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9"}
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9"}
sp-application-crypto = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9"}
frame-support = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.9"}

[features]
default = ["std"]
std = [
  "codec/std",
  "frame-system/std",
 	"sp-application-crypto/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-std/std"
]