[profile.release]
panic = 'unwind'

[workspace]
members = [
	"primitives",
	"runtime",
	"rpc",
	"executor",
	"inspect",
	"node",
	"pallets/did",
	"pallets/registrar",
	"pallets/entity",
	"pallets/space",
	"pallets/schema",
	"pallets/journal",
	"pallets/stream",
	"pallets/streamlink",
	"pallets/streamdigest",
]

