[profile.release]
panic = 'unwind'

[workspace]
members = [
	"primitives",
	"runtime",
	"rpc",
	"executor",
	"inspect",
	"node",
	"pallets/mtype",
	"pallets/delegation",
	"pallets/did",
	"pallets/mark",
]

