[package]
name = 'pallet-did'
version = '0.5.0'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']
description = 'Enables adding and removing decentralized identifiers (DIDs).'

[[package.metadata.docs.rs]]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[dev-dependencies]
serde = { version = "1.0.123" }
env_logger = {version = "0.8.3"}
cord-primitives = { package = "cord-primitives", default-features = false, path = "../../primitives"}
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false }
pallet-mtype = {features = ["mock"], path = "../mtype"}

[dependencies]
codec = {default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
cord-primitives = { package = "cord-primitives", path="../../primitives", version = "0.5.0", optional = true, default-features = false }
serde = { version = "1.0.123", optional = true}
env_logger = {optional = true, default-features = false, version = "0.8.3"}
log = {default-features = false, version = "0.4.14"}
hex = {default-features = false, features = ["alloc"], version = "0.4.2"}
pallet-mtype = {features = ["mock"], optional = true, path = "../mtype"}

# Substrate dependencies
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false, optional = true}
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false, optional = true}
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false, optional = true}
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5", default-features = false }

[features]
default = [ 'std' ]
mock = [
  "pallet-mtype",
  "env_logger",
  "cord-primitives",
  "serde",
  "sp-io",
  "sp-keystore"
]
runtime-benchmarks = [
  "frame-benchmarking",
  "sp-io"
]
std = [
  "codec/std",
  "frame-support/std",
  "frame-system/std",
  "hex/std",
  "log/std",
  "sp-core/std",
  "sp-keystore/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
]