[package]
name = 'pallet-did'
version = '0.4.0'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']
description = 'Enables adding and removing decentralized identifiers (DIDs).'

[[package.metadata.docs.rs]]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder = { package = 'substrate-wasm-builder', version = '3.0.0' }

[dependencies]
codec = {default-features = false,features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }

# Substrate dependencies
frame-support = {  version = "3.0.0", default-features = false }
frame-system = {  version = "3.0.0", default-features = false }
sp-runtime = {  version = "3.0.0", default-features = false }
sp-std = {  version = "3.0.0", default-features = false }
frame-benchmarking = {  version = "3.0.0", default-features = false , optional = true}


[dev-dependencies]
serde = { version = "1.0", default-features = false }
sp-core = {  version = "3.0.0", default-features = false }
sp-io = {  version = "3.0.0", default-features = false }

[features]
default = [ 'std' ]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-std/std',
]
