[package]
name = 'cord-node-runtime'
version = '0.2.0'
build = 'build.rs'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']

[[package.metadata.docs.rs]]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder-runner = { package = 'substrate-wasm-builder-runner', version = '2.0.0' }

[dependencies]
smallvec = "1.4.0"
hex-literal = { optional = true, version = '0.3.1' }
serde = { features = ['derive'], optional = true, version = '1.0.101' }
bitflags = { default-features = false, version = '1.2.1' }
parity-scale-codec = { version = "1.3.4", default-features = false, features = ["derive"] }

# local dependencies
attestation = { version = '0.23.0', default-features = false, path = '../pallets/attestation' }
ctype = { version = '0.23.0', default-features = false, path = '../pallets/ctype' }
delegation = { version = '0.23.0', default-features = false, path = '../pallets/delegation' }
did = { version = '0.23.0', default-features = false, path = '../pallets/did' }
error = { version = '0.23.0', default-features = false, path = '../pallets/error' }
portablegabi = { version = '0.23.0', default-features = false, path = '../pallets/portablegabi' }
primitives = { package = "cord-primitives", version = "0.2.0", path = "../primitives", default-features = false }

# Substrate dependencies
frame-benchmarking = { default-features = false, optional = true, version = '2.0.0' }
frame-executive = { default-features = false, version = '2.0.0' }
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }
frame-system-benchmarking = { default-features = false, optional = true, version = '2.0.0' }
frame-system-rpc-runtime-api = { default-features = false, version = '2.0.0' }
pallet-aura = { default-features = false, version = '2.0.0' }
pallet-authorship = { default-features = false, version = '2.0.0' }
pallet-balances = { default-features = false, version = '2.0.0' }
pallet-grandpa = { default-features = false, version = '2.0.0' }
pallet-randomness-collective-flip = { default-features = false, version = '2.0.0' }
pallet-sudo = { default-features = false, version = '2.0.0' }
pallet-timestamp = { default-features = false, version = '2.0.0' }
pallet-transaction-payment = { default-features = false, version = '2.0.0' }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = '2.0.0' }
pallet-session = { default-features = false, version = '2.0.0' }
pallet-indices = { default-features = false, version = '2.0.0' }
pallet-authority-discovery = { default-features = false, version = '2.0.0' }
pallet-finality-tracker = { default-features = false, version = '2.0.0' }
pallet-offences = { version = "2.0.0", default-features = false }
sp-api = { default-features = false, version = '2.0.0' }
sp-block-builder = { default-features = false, version = '2.0.0' }
sp-consensus-aura = { default-features = false, version = '0.8.0' }
sp-core = { default-features = false, version = '2.0.0' }
sp-inherents = { default-features = false, version = '2.0.0' }
sp-offchain = { default-features = false, version = '2.0.0' }
sp-runtime = { default-features = false, version = '2.0.0' }
sp-session = { default-features = false, version = '2.0.0' }
sp-std = { default-features = false, version = '2.0.0' }
sp-transaction-pool = { default-features = false, version = '2.0.0' }
sp-version = { default-features = false, version = '2.0.0' }

[features]
default = ['std']
runtime-benchmarks = [
    'hex-literal',
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]
std = [
    'parity-scale-codec/std',
    'serde/std',
   	"primitives/std",
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'pallet-authority-discovery/std',
    'pallet-finality-tracker/std',
    'pallet-offences/std',
    'pallet-aura/std',
    'pallet-balances/std',
    'pallet-indices/std',
	'pallet-grandpa/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
	'sp-transaction-pool/std',
    'sp-version/std',
	'attestation/std',
	'ctype/std',
	'did/std',
	'error/std',
	'delegation/std',
	'portablegabi/std',
]
