[package]
name = 'cord-node'
version = '0.5.0'
build = 'build.rs'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = 'cord'
path = "src/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.123", features = ["derive"] }
futures = { version = "0.3.9", features = ["compat"] }
hex-literal = "0.3.1"
log = "0.4.8"
rand = "0.8.3"
structopt = { version = "0.3.8", optional = true }
parking_lot = "0.11.1"

sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.7" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

#sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
#sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
#sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
#sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
#sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
#sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
#sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
#sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7", default-features = false }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7", optional = true }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-finality-grandpa-warp-sync = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7", optional = true }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

# Substrate Pallets
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }


# node-specific dependencies
cord-runtime = { package = "cord-runtime", path = "../runtime", version = "0.5.0" }
cord-primitives = { package = "cord-primitives", path="../primitives", version = "0.5.0" }
cord-executor = { package = "cord-executor", path = "../executor", version = "0.5.0" }
cord-inspect = { package = "cord-inspect", path = "../inspect", version = "0.5.0" }
cord-rpc = { package = "cord-rpc", path = "../rpc", version = "0.5.0" }

# CLI-specific dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.7" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.7" }

[target.'cfg(target_arch="x86_64")'.dependencies]
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7", optional = true, features = [ "wasmtime" ] }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7", optional = true, features = [ "wasmtime" ] }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7", optional = true, features = ["memory-tracker"] }

# Substrate Other
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

[dev-dependencies]
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-service-test = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
futures = "0.3.9"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.19"
serde_json = "1.0"
regex = "1"
platforms = "1.1"
async-std = { version = "1.6.5", features = ["attributes"] }
soketto = "0.4.2"

[build-dependencies]
structopt = { version = "0.3.8", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.7" }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.7"}
substrate-frame-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.7" }

[features]
default = [ "cli" ]
cli = [
	"cord-executor/wasmi-errno",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/db",
	"sc-finality-grandpa-warp-sync",
	"structopt",
	"substrate-build-script-utils",
]
runtime-benchmarks = [
  "cord-runtime/runtime-benchmarks",
]
