[package]
name = 'cord-node'
version = '0.2.0'
build = 'build.rs'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']

[[bin]]
name = 'cord-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '2.0.0'

[dependencies]
jsonrpc-core = '15.1.0'
futures = "0.3.8"
hex-literal = "0.3.1"
structopt = '0.3.21'
log = "0.4.11"

# local dependencies
cord-node-runtime = {path = '../runtime'}
primitives = { package = "cord-primitives", path = "../primitives", default-features = false }

# Substrate dependencies
frame-benchmarking = {git = 'https://github.com/paritytech/substrate.git', branch = "master"}
frame-benchmarking-cli = {git = 'https://github.com/paritytech/substrate.git', branch = "master"}
frame-rpc-system = {package = 'substrate-frame-rpc-system', git = 'https://github.com/paritytech/substrate', branch = "master"}

pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-cli = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-client-api = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-consensus = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-executor = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-keystore = {git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-network = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-rpc = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-rpc-api = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-service = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-api = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-block-builder = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-blockchain = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-consensus = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-core =  { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-inherents = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-runtime = {git = 'https://github.com/paritytech/substrate', branch = "master"}
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = "master"}
