[package]
name = 'cord-node'
version = '0.3.1'
build = 'build.rs'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[[bin]]
name = 'cord'
path = "src/main.rs"

[build-dependencies]
substrate-build-script-utils = '3.0.0'

[dependencies]

# External Crates
futures = "0.3.12"
hex-literal = "0.3.1"
tracing = "0.1.22"
tracing-futures = "0.2.4"
serde = { version = "1.0.123", features = ["derive"] }
thiserror = "1.0.23"
structopt = '0.3.21'
jsonrpc-core = "15.1.0"

# node-specific dependencies
cord-runtime = { path = "../runtime" }
cord-primitives = { package = "cord-primitives", path = "../primitives", default-features = false }

# Substrate Client
sc-authority-discovery = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-block-builder = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-finality-grandpa-warp-sync = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-service = { git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-keystore = {git = 'https://github.com/paritytech/substrate', branch = "master"}
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "master" }

# Substrate Primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "master"  }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master"  }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }

# Substrate Pallets
pallet-aura = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-im-online = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }

# Substrate Other
frame-system = { git = "https://github.com/paritytech/substrate", branch = "master" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
frame-benchmarking = {git = 'https://github.com/paritytech/substrate.git', branch = "master"}
frame-benchmarking-cli = {git = 'https://github.com/paritytech/substrate.git', branch = "master"}
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
frame-rpc-system = {package = 'substrate-frame-rpc-system', git = 'https://github.com/paritytech/substrate', branch = "master"}
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "master" }


#sp-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
#sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "master" }

# client dependencies
#sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "master"}
#sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
#sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "master" }

#pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "master" }
#pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
#pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "master" }

#pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "master" }
#pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
