[package]
name = 'cord'
version = '0.4.0'
build = 'build.rs'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[[bin]]
name = 'cord'
path = "src/main.rs"

[build-dependencies]
substrate-build-script-utils = '3.0.0'

[dependencies]

# External Crates
futures = "0.3.12"
hex-literal = "0.3.1"
tracing = "0.1.22"
tracing-futures = "0.2.4"
serde = { version = "1.0.123", features = ["derive"] }
thiserror = "1.0.23"
structopt = '0.3.21'
jsonrpc-core = "15.1.0"

# node-specific dependencies
cord-runtime = { path = "../runtime" }
cord-primitives = { package = "cord-primitives", path = "../primitives", default-features = false }

# Substrate Client
sc-authority-discovery = { version = "0.9.0", default-features = false}
sc-consensus-aura = { version = "0.9.0" }
sc-finality-grandpa = { version = "0.9.0" }
sc-finality-grandpa-rpc = { version = "0.9.0" }
sc-block-builder = { version = "0.9.0" }
sc-chain-spec = { version = "3.0.0" }
sc-client-api = { version = "3.0.0" }
sc-client-db = { version = "0.9.0" }
sc-consensus = { version = "0.9.0" }
sc-executor = { version = "0.9.0" }
sc-network = { version = "0.9.0" }
sc-transaction-pool = { version = "3.0.0" }
sc-service = { version = "0.9.0" }
sc-telemetry = { version = "3.0.0" }
sc-rpc = { version = "3.0.0" }
sc-rpc-api = { version = "0.9.0" }
sc-cli = { version = "0.9.0" }
sc-keystore = { version = "3.0.0" }
sc-basic-authorship = { version = "0.9.0" }

# Substrate Primitives
sp-authority-discovery = { version = "3.0.0" }
sp-consensus-aura = { version = "0.9.0" }
sp-consensus = { version = "0.9.0" }
sp-finality-grandpa = { version = "3.0.0" }
sp-inherents = { version = "3.0.0" }
sp-api = { version = "3.0.0" }
sp-block-builder = { version = "3.0.0" }
sp-blockchain = { version = "3.0.0" }
sp-core = { version = "3.0.0" }
sp-io = { version = "3.0.0" }
sp-keystore = { version = "0.9.0" }
sp-offchain = { version = "3.0.0", package = "sp-offchain" }
sp-runtime = { version = "3.0.0" }
sp-session = { version = "3.0.0" }
sp-storage = { version = "3.0.0" }
sp-transaction-pool = { version = "3.0.0" }

# Substrate Pallets
pallet-aura = { version = "3.0.0" }
pallet-im-online = { version = "3.0.0", default-features = false }
pallet-staking = { version = "3.0.0" }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0" }
pallet-transaction-payment = { version = "3.0.0" }
pallet-transaction-payment-rpc = { version = "3.0.0" }

# Substrate Other
frame-system = { version = "3.0.0" }
frame-support = { version = "3.0.0", default-features = false }
frame-benchmarking = { version = "3.0.0" }
frame-benchmarking-cli = { version = "3.0.0" }
frame-system-rpc-runtime-api = { version = "3.0.0"  }
frame-rpc-system = { version = "3.0.0",package = 'substrate-frame-rpc-system' }
prometheus-endpoint = { version = "0.9.0", package = "substrate-prometheus-endpoint"  }

[features]
default = []
runtime-benchmarks = [
  "cord-runtime/runtime-benchmarks",
]