[package]
name = 'cord-executor'
version = '0.5.1'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0"}
cord-runtime = { package = "cord-runtime", path = "../runtime", version = "0.5.0" }
cord-primitives = { package = "cord-primitives", path="../primitives", version = "0.5.0" }

sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
trie-root = "0.16.0"
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

[dev-dependencies]
criterion = "0.3.0"
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
wat = "1.0"
futures = "0.3.9"

[features]
wasmtime = [
	"sc-executor/wasmtime",
]
wasmi-errno = [
	"sc-executor/wasmi-errno",
]
