[package]
name = 'pallet-stream-link'
version = '0.5.2'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']
description = 'Enables adding and linking transactions to streams.'

[[package.metadata.docs.rs]]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[dependencies]
codec = {default-features = false,features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8", optional = true }
log = {default-features = false, version = "0.4.14"}
serde = {default-features = false, optional = true, version = "1.0.125"}
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8", optional = true }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8", optional = true }
sp-keystore = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8", optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }

# Internal Dependencies
pallet-schema = { default-features = false, path = '../schema' }
pallet-stream = { default-features = false, path = '../stream' }
cord-primitives = {default-features = false, optional = true, path = "../../primitives"}

[dev-dependencies]
pallet-schema = {features = ["mock"], path = "../schema" }
pallet-stream = {features = ["mock"], path = "../stream" }
cord-primitives = {default-features = false, path = "../../primitives"}
serde = {default-features = false, version = "1.0.125"}
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
sp-keystore = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }

[features]
default = [ 'std' ]
mock = [
	"cord-primitives",
	"serde",
	"sp-core",
	"sp-io",
	"sp-keystore"
]
runtime-benchmarks = [
	"frame-benchmarking",
  	"frame-system/runtime-benchmarks",
  	"frame-support/runtime-benchmarks",
  	"sp-core"
]
std = [
	'codec/std',
	'pallet-schema/std',
	'pallet-stream/std',
	'frame-support/std',
	'frame-system/std',
	'cord-primitives/std',
	'log/std',
	'sp-core/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',	
]