# This is a basic workflow to help you get started with Actions

name: CI

# Control when the action will run. 
on:
  # Trigger the workflow on push event
  push:
    branches: [ "*" ]

  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Skip based on commit message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    # A map of envvironment variables available to all steps in the job
    env:
      ECR_LOGIN_SERVER: 398701577843.dkr.ecr.ap-south-1.amazonaws.com
      ACR_LOGIN_SERVER: 2pzinx547jo6coxz.azurecr.io
      IMAGE_REPOSITORY: ${{ github.event.repository.name }}
      IMAGE_TAG: ${{ github.sha }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login to Amazon ECR
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_LOGIN_SERVER }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Login to Azure ACR
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.SP_APP_ID }}
          password: ${{ secrets.SP_PASSWD }}

      # Push image to Registry
      - run: |
          docker build --no-cache --file Dockerfile --tag ${{ env.IMAGE_REPOSITORY }}:latest .
          
          docker tag ${{ env.IMAGE_REPOSITORY }}:latest $ECR_LOGIN_SERVER/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }} && \
          docker tag ${{ env.IMAGE_REPOSITORY }}:latest $ECR_LOGIN_SERVER/${{ env.IMAGE_REPOSITORY }}:latest
          
          docker push $ECR_LOGIN_SERVER/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }} && \
          docker push $ECR_LOGIN_SERVER/${{ env.IMAGE_REPOSITORY }}:latest
          
          docker tag ${{ env.IMAGE_REPOSITORY }}:latest $ACR_LOGIN_SERVER/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }} && \
          docker tag ${{ env.IMAGE_REPOSITORY }}:latest $ACR_LOGIN_SERVER/${{ env.IMAGE_REPOSITORY }}:latest
          
          docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }} && \
          docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_REPOSITORY }}:latest
