[package]
name = 'pallet-delegation'
version = '0.5.0'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']
description = 'Enables creating and revoking root & delegation nodes of consortium hierarchies'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = "4.0.0"

#substrate-wasm-builder-runner = {version = "3.0.0"}

[dependencies]
codec = {default-features = false,features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
serde = { version = "1.0.123", optional = true, features = ["derive"] }
bitflags = { default-features = false, version = '1.2.1' }
log = {default-features = false, version = "0.4.14"}

# Substrate dependencies
frame-support = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate"}
frame-system = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate"}
frame-benchmarking = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate", optional = true}
sp-core = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate", optional = true}
sp-io = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate", optional = true}
sp-keystore = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate", optional = true}
sp-runtime = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate"}
sp-std = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate"}

# local pallets
pallet-mtype = { version = "0.5.0", default-features = false, path = '../mtype' }
cord-primitives = { package = "cord-primitives", default-features = false, optional = true, path = "../../primitives"}

[dev-dependencies]
serde = { version = "1.0.123", default-features = false }
sp-core = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate", version = "3.0.0"}
sp-keystore = {branch = "polkadot-v0.9.7", default-features = false, git = "https://github.com/paritytech/substrate"}
pallet-mtype = {features = ["mock"], path = "../mtype"}
cord-primitives = { package = "cord-primitives", default-features = false, path = "../../primitives"}


[features]
default = [ 'std' ]
mock = [
  "cord-primitives",
  "serde",
  "sp-core",
  "sp-io",
  "sp-keystore"
]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sp-core",
  "sp-io"
]
std = [
	'codec/std',
	'pallet-mtype/std',
	'frame-support/std',
	'frame-system/std',
	"cord-primitives/std",
  "log/std",
  "sp-core/std",
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
]
