[package]
name = 'pallet-delegation'
version = '0.4.0'
edition = '2018'
authors = ['Dhiway <info@dhiway.com>']
description = 'Enables creating and revoking root & delegation nodes of consortium hierarchies'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder = { package = 'substrate-wasm-builder', version = '3.0.0' }

[dependencies]
codec = {default-features = false,features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
bitflags = { default-features = false, version = '1.2.1' }
cord-primitives = {  version = "0.4.0",package = "cord-primitives", path = "../../primitives", default-features = false }
sp-core = { version = "3.0.0", default-features = false , optional = true}


# Substrate dependencies
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
frame-benchmarking = {  version = "3.0.0", default-features = false , optional = true}


# local pallets
pallet-mtype = { version = "0.4.0", default-features = false, path = '../mtype' }

[dev-dependencies]
serde = { version = "1.0", default-features = false }

[features]
default = [ 'std' ]
runtime-benchmarks = [
  "frame-benchmarking",
  "sp-core",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-mtype/runtime-benchmarks",
]
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-runtime/std',
	'sp-std/std',
	'sp-io/std',
	'pallet-mtype/std',
]
